# Generated by Django 4.1.7 on 2023-02-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subtitle', models.CharField(max_length=100)),
                ('subdescription', models.TextField()),
                ('snippet', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=100)),
                ('tag', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='photos')),
                ('image2', models.ImageField(upload_to='photos')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
